# Generated by Django 5.2 on 2025-11-23 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_newsletter_options_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_post_id_5fee65_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_parent__43ce68_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_slug_cdb902_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_is_feat_837e2e_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='blue', help_text='Tailwind color name', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
